### ISSUE TITLE
Have the package version accessible as `endaq.__version__` 

### ISSUE THREAD

**Issue by SamRagusa** [MideTechnology/endaq-python#120]
This package's version number should be accessible via the `.__version__` attribute of the `endaq` module

How we want to do this is something I expect people to have thoughts on, so I figured I'd make this issue rather than just implement one of the approaches and cause chaos in a PR.

There's several options for doing this that are laid out in the following python.org page  (personally I like #1, and the note about it seems promising, though I haven't tried it):
https://packaging.python.org/en/latest/guides/single-sourcing-package-version/

**Comment by CFlaniganMide** [comment]
numpy uses [versioneer](https://github.com/python-versioneer/python-versioneer)
I remember looking at it a while ago and thinking that it looked good.
