### ISSUE TITLE
Pandas minimum version required?

### ISSUE THREAD

**Issue by scdwyer** [MideTechnology/endaq-python#14]
I attempted to use endaq.ide.get_channel_table() but a TypeError exception was raised:
````
c:\tools\python37\lib\site-packages\endaq\ide\info.py in get_channel_table(dataset, measurement_type, start, end, formatting, index, precision, timestamps, **kwargs)
    287         style.update(formatting)
    288 
--> 289     styled = pd.DataFrame(result).style.format(style, precision=precision)
    290     if not index:
    291         return styled.hide_index()

TypeError: format() got an unexpected keyword argument 'precision'
````

I think this requires a newer version of pandas than I was running (1.2.4). What is the minimum version required?

**Comment by StokesMIDE** [comment]
@scdwyer Coincidentally, I was just addressing this in a `endaq-python-ide` PR... The new requirements will explicitly specify `pandas>=1.3`.

**Comment by StokesMIDE** [comment]
BTW @scdwyer: I think yours may be the first issue on one of our open source repos originating out-of-house. Thanks for the input!

**Comment by Anay21110** [comment]
Yes , it clearly mentions `pandas>=1.3` as minimum requirement.

I hope @StokesMIDE and I have solved you issue.

**Comment by pscheidler** [comment]
The Pandas version is explicitly required in our latest release, so I am closing the issue
