### ISSUE TITLE
Research using Jupyter notebook in docs

### ISSUE THREAD

**Issue by pscheidler** [MideTechnology/endaq-python#144]

**Comment by CFlaniganMide** [comment]
Example from Tensorflow (Thanks to Sam for showing this to me)
https://www.tensorflow.org/tutorials/images/transfer_learning
https://github.com/tensorflow/docs/blob/master/site/en/r1/tutorials/images/transfer_learning.ipynb

https://nbsphinx.readthedocs.io/en/0.8.8/index.html
