### ISSUE TITLE
Segregate Large Time Series into Shock or Vibration Portions, then Run PVSS or PSD for Each

### ISSUE THREAD

**Issue by S-Hanly** [MideTechnology/endaq-python#156]
[Inspired from this article](https://www.osti.gov/biblio/1642883) that recommends taking a large time series and segregating into either shock or vibration periods via a skyline approach identified with either:

- RMS
- Kurtosis
- Peak
![image](https://user-images.githubusercontent.com/35080650/151266186-3b978bb7-f013-4753-9dc9-b225364da7c1.png)

Then compute a waterfall plot (line for each segment) for the various shock and vibration profiles.
![image](https://user-images.githubusercontent.com/35080650/151266298-9375ae24-e0ff-48d6-87da-eab83df56c81.png)
[1642883.pdf](https://github.com/MideTechnology/endaq-python/files/7946411/1642883.pdf)

Note that this would automate what many enDAQ customers are looking to do:

- From a large time series
- Define a SRS to represent the environment
- Define a PSD to represent the environment
- Understand the consistency of above environments (remove outliers for example)

**Comment by pscheidler** [comment]
Discussed in meeting: this will be a separate function from PVSS, but the output can be fed into PVSS for processing
