### ISSUE TITLE
RuntimeWarning & ValueError when using endaq.plot.octave_spectrogram()

### ISSUE THREAD

**Issue by MarcelEckh** [MideTechnology/endaq-python#189]
The Webinar I'm referring to: [link](https://colab.research.google.com/drive/1WAtQ8JJC_ny0fki7eUABACMA-isZzKB6#scrollTo=FXK_Jm3oUiqD)
I can't attach the Jupyter Lab script nor the csv file, however the csv file is available [here](https://info.endaq.com/hubfs/data/motorcycle-vibration-moving-frequency.csv)
I'm using a Jupyter Lab script with Python 3.9.11 (installed with [asdf](http://asdf-vm.com/guide/getting-started.html#_1-install-dependencies))

I measured vibration and I now want to analyze the data using the endaq python library. Unfortunately, I can't use the endaq.plot.octave_spectrogram() method. When I realized that (until now) only this method is not working I downloaded the file from the introduction Webinar for the library and copied the code as well. Even then, with the exact same code and data I get these Errors. I tried other methods which are mentioned previously in the Webinar and they work fine. Below is a minimum working example with the mentioned csv file and the `endaq.plot.plots.rolling_min_max_envelope()` method. I also added `endaq.plot.octave_spectrogram()` which is not working for me.
I also tested this on my private Windows PC with the same Python Version which was not installed with asdf. Same result. Every mehtod I tested works except `endaq.plot.octave_spectrogram()`.
Yes, the csv file is in the same folder, I also tested it with only using the link like in the Webinar... no difference.

Minimum example:
```python
# working part
import endaq

import plotly.express as px
import plotly.graph_objects as go
import pandas as pd
import numpy as np
import scipy

df_vibe = pd.read_csv('motorcycle-vibration-moving-frequency.csv',index_col=0)
df_vibe = df_vibe - df_vibe.median()
df_vibe

accel_time_labels = dict(
    xaxis_title_text='',
    yaxis_title_text='Acceleration (g)',
    legend_title_text=''
)

fig = endaq.plot.plots.rolling_min_max_envelope(
    df_vibe,
    desired_num_points=1000,
    plot_as_bars=True,
    opacity=1.0
    )
fig.update_layout(
    accel_time_labels,
    title_text='Engine Reving of Motorcycle',
)
fig.show()

# not working part
freqs, bins, Pxx, fig = endaq.plot.octave_spectrogram(df_vibe[['Z (40g)']], 
                                                      window=0.5, 
                                                      bins_per_octave=12, 
                                                      max_freq=1000, 
                                                      freq_start=40)
fig.show()

```

Error Message:
`/home/marcel/.asdf/installs/python/3.9.11/lib/python3.9/site-packages/endaq/calc/psd.py:169: RuntimeWarning:

empty frequency bins in re-binned PSD; original PSD's frequency spacing is too coarse

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Input In [7], in <cell line: 1>()
----> 1 freqs, bins, Pxx, fig = endaq.plot.octave_spectrogram(df_vibe[['Z (40g)']], 
      2                                                       window=0.5, 
      3                                                       bins_per_octave=12, 
      4                                                       max_freq=1000, 
      5                                                       freq_start=40)
      6 fig.show()

ValueError: not enough values to unpack (expected 4, got 2)`

**Comment by shanlyMIDE** [comment]
Hey @MarcelEckh, first off thank you for officially being the first non-enDAQ person to post an issue here! It's a first but not a last and although I don't want to diminish the frustration you are undoubtedly feeling, I'm excited that this is the beginning of accelerated adoption of our library! Sorry it has taken us so long to see this, I'll change my settings in GitHub to get notified every time an issue is posted! I'm also going to at my fellow contributors: @StokesMIDE @CFlaniganMide @pscheidler  

I'm not a big fan of the implementation of this function, I had posted a related issue actually: #35. More on that next after I help fix the immediate issue.

The runtime errors are more messages than errors to let you know that the PSD is too coarse for the given time range. They are admittedly annoying but they can be ignored as they are "just" warnings. The software team won't like this too much but you can explicitly turn them off via (found on [stackoverflow](https://stackoverflow.com/questions/14463277/how-to-disable-python-warnings)):
```
import warnings
warnings.filterwarnings("ignore")
```

The actual error you have is that the function was updated to only return two parameters not 4 so you need to change the line:
`freqs, bins, Pxx, fig = endaq.plot.octave_spectrogram(df_vibe[['Z (40g)']]`
to 
`df, fig = endaq.plot.octave_spectrogram(df_vibe[['Z (40g)']]`

I showed an example of it running correctly in this colab ([here's the link](https://colab.research.google.com/drive/15K135a51bMCN1QbLbrnUCpb4dJYVBMqP?usp=sharing)).

Now to how we can improve this function! I had a few issues with the current implementation:
- The returned data isn't actually in real engineering units that you can relate to anything else
- There is no ability to customize your display, see options below (all in that colab)

I really don't like that this function does a lot of calculations in the plotting module, I'd rather have `rolling_psd`, `rolling_fft`, `rolling_srs` functions in `endaq.calc` and then a single `plot.3d_spectrum` function that allows the users to pass the output from one of the calc functions to it. I'll clean some of this code up in the colab and do a pull request tomorrow and at you to be aware we are acting on your feedback! Speaking of, please let me know if you like or dislike what I'm proposing!


![newplot - 2022-04-05T215730 699](https://user-images.githubusercontent.com/35080650/161883366-bff11e61-9f0a-4ecc-9a2b-ed4f26807393.png)


![newplot - 2022-04-05T215719 993](https://user-images.githubusercontent.com/35080650/161883389-2c909c73-ca71-4815-82c3-7dd41881ba16.png)

![newplot - 2022-04-05T222253 942](https://user-images.githubusercontent.com/35080650/161883421-b4d3ced2-989a-40d0-8a00-a0415da992f9.png)

**Comment by shanlyMIDE** [comment]
@MarcelEckh I wanted to give you an update that I'm getting somewhere with some new functions but won't finish tonight, here's the [work in progress](https://colab.research.google.com/drive/1pSA2F9AYimuAn5Xijws8RVbX3tMY2Gha?usp=sharing) if you want to check it out! What I have left to do is:

- [ ] Add a `rolling_shock_spectrum` function and test
- [ ] Add some simple examples into the docstrings ([lots of examples are in the colab already though!](https://colab.research.google.com/drive/1pSA2F9AYimuAn5Xijws8RVbX3tMY2Gha?usp=sharing)) 
- [ ] Build a new branch, test, and submit a pull request!

![image](https://user-images.githubusercontent.com/35080650/162101566-4faa6c33-88ea-4854-acdc-acdc0278dcf6.png)
![image](https://user-images.githubusercontent.com/35080650/162101579-212af87a-812c-499c-a6a4-5981af4776e0.png)
![image](https://user-images.githubusercontent.com/35080650/162101669-5bbb24ec-d543-4102-8d52-4126f3869888.png)
![image](https://user-images.githubusercontent.com/35080650/162101737-6088af52-9421-4171-a966-1471fec498fc.png)
![image](https://user-images.githubusercontent.com/35080650/162101776-57c026ba-20c6-4421-8fd2-f00b06651b57.png)

**Comment by MarcelEckh** [comment]
Hi @shanlyMIDE, I feel honored by your reply and it's absolutely great to get such good help so quickly! Thank you very much for that!
The colab you created also helps a ton and I was able to correct my code and now it works. To be honest, I completely missed the changes that were being done to this function.

Regarding your proposals: I really like them and I'd especially appreciate having the returned data in actual units.

**Comment by shanlyMIDE** [comment]
Alright it's been submitted! We'll let you know when we have something fully merged into development, but you can download and test this specific branch

**Comment by MarcelEckh** [comment]
Awesome! I look forward to it.

**Comment by shanlyMIDE** [comment]
closing this now because it is in development! https://github.com/MideTechnology/endaq-python/pull/191

Here is the specific major function (that links to a lot of the other new ones): https://docs.endaq.com/en/development/endaq/plot.html#endaq.plot.spectrum_over_time

You can download this branch via:
```
pip install git+https://github.com/MideTechnology/endaq-python.git@development
```
