### ISSUE TITLE
Max, Min, Mean Values Not Calibrated in `endaq.ide.get_file_table()`

### ISSUE THREAD

**Issue by shanlyMIDE** [MideTechnology/endaq-python#28]
It seems the values don't apply the calibration polynomials, see example:

![image](https://user-images.githubusercontent.com/35080650/132435250-36c880bd-4607-4b3c-9498-d459af668678.png)

**Comment by StokesMIDE** [comment]
This was an `idelib` issue which has been fixed in [`idelib` PR 89](https://github.com/MideTechnology/idelib/pull/89). However, the temporary fix was to remove the min/mean/max columns from the table. Putting them back in should be a new 'enhancement' issue.
