### ISSUE TITLE
Tripartite or 4 Coordinate Plot for Shock Response Spectrums

### ISSUE THREAD

**Issue by S-Hanly** [MideTechnology/endaq-python#33]
More information and examples: 
- https://www.dplot.com/tripartite.htm
- https://vibrationdata.wordpress.com/2012/10/30/srs-tripartite-format/
![image](https://user-images.githubusercontent.com/35080650/135288127-e259dbf2-3ad6-4e6e-a413-1c07550ef09d.png)

**Comment by shanlyMIDE** [comment]
@SamRagusa @CFlaniganMide  when adding lines to plotly with graph objects you would need to include the following two parameters:
```
      showlegend=False,
      hoverinfo='skip',
```
To not do the hover stuff and not include them in the legend. Here's the colab where I did this: https://colab.research.google.com/drive/1WtBQLKeqZm9Ehbdbgn5V-o5Cyk_rUZo6#scrollTo=5LouD8Qics4U

You'll notice that no hover information displays for the diagnol lines and the hover information does now display the displacement and peak acceleration.

![image](https://user-images.githubusercontent.com/35080650/146067410-78ced36d-80e0-4c50-ac39-31c5f6e85e96.png)

cc: @StokesMIDE @CrepeGoat @pscheidler
