### ISSUE TITLE
Resampling Function Defined by Desired Sample Rate

### ISSUE THREAD

**Issue by shanlyMIDE** [MideTechnology/endaq-python#44]
When resampling a typical mechanical engineer will have a dataset with some unknown sample rate and they may want to explicitly define a sample rate (either decimated or upsampled) to match other datasets they have.  

I know this is super simple but can we have a function with two inputs:

- Dataframe indexed with time (either datetimes, floats in seconds, or timedeltas)
- Desired end sample rate defined in Hz

Then this function will resample to get the desired end sample rate. Here is some code example that is using a new function in the development branch `sample_spacing` (https://github.com/MideTechnology/endaq-python-calc/blob/development/endaq/calc/utils.py).

~~~python
def resample(df,sample_rate):
  """Resample a dataframe to a desired sample rate (in Hz)"""
  fs = get_sample_rate(df)
  num_samples_after_resampling = int(len(df)/fs*sample_rate)
  resampled_data, resampled_time = scipy.signal.resample(df,
                                                       num_samples_after_resampling,
                                                       t=df.index)
  resampled_df = pd.DataFrame(resampled_data,
                            index=resampled_time,
                            columns=df.columns)
  return resampled_df
~~~

**Comment by pscheidler** [comment]
@SamRagusa did it
