### ISSUE TITLE
VC Curve Bug

### ISSUE THREAD

**Issue by shanlyMIDE** [MideTechnology/endaq-python#51]
In this repo you are calculating the VC data with (https://github.com/MideTechnology/endaq-python-calc/blob/92dfae335542869489a60ac498373baeb6ff2055/endaq/calc/psd.py#L281)

`return np.sqrt(accel_psd.index[1]) * df_vel_oct.apply(np.sqrt)`

Yet in the OG repo (https://github.com/MideTechnology/endaq-vc-curves/blob/c128637518d5b162efc27d3449fb6be39a47f4fb/bsvp/analyzer.py#L360) it is:
`v_vc = np.sqrt(f[1] * v_psd_oct)  # the PSD must already scale by ∆f?`

@CrepeGoat you'll notice that in the current code you are applying the scalar _after_ taking the square root whereas before it was _before_.

**Comment by pscheidler** [comment]
@shanlyMIDE Can you re-run the test and see if this is still a bug? @CrepeGoat has made some changes but not clear if it has really been fixed

**Comment by shanlyMIDE** [comment]
@pscheidler @CrepeGoat  there is still very much a bug. I can manually calculate the VC curves with defining different `agg` methods. The `vc_curve` function erroneously uses `np.sum`
https://colab.research.google.com/drive/1hvH4JndUYyDu94xq3lnXyfHgAkptMBEf?usp=sharing

Here's a plot comparing (there are two lines on top of each other)

![newplot - 2021-12-15T151918 409](https://user-images.githubusercontent.com/35080650/146259097-c1d817bc-7594-4795-889b-1f05f55a85ef.png)

This may be a good candidate for me to do a pr, watch out!
