### ISSUE TITLE
Caches will become out of date overtime, reducing their utility.

### ISSUE THREAD

**Issue by CFlaniganMide** [MideTechnology/endaq-python#59]
The key for the cache on the dependencies may not change if `setup.py` or `requirements.txt` are not changed.  Given the pip upgrade flags, this won't mean we're testing against old versions (which is good), but it also means that we may just effectively by paying for storage we aren't getting value out of.

So, proposed solutions:
- Add a script to add the date (or possibly just the week) to the key, so the cache rotates regularly, but we still benefit substantially.
- Get pip to solve the requirements and add that to the hash calculation.  That way we'll update the cache whenever our dependencies are updated.

**Comment by CrepeGoat** [comment]
1. accomplished in f0edbc997c6726631fb4b79c62cb1a374e80fc16
2. I'd prefer this, but I don't see that functionality in pip currently :\

**Comment by pscheidler** [comment]
Cache is updated once per week
