### ISSUE TITLE
add use-case examples to docs

### ISSUE THREAD

**Issue by CrepeGoat** [MideTechnology/endaq-python#85]
It would be beneficial for users to have some runnable examples of `endaq` for common use-cases, as determined by @shanlyMIDE & customer success.

**Comment by CrepeGoat** [comment]
It'd also be nice to run these examples in our test framework, to ensure that the examples we provide are up-to-date and working. (There's nothing worse than trying out a package by running a code example that the developers provided you, and having it just error out.)

**Comment by shanlyMIDE** [comment]
I think we can close this from https://github.com/MideTechnology/endaq-python/pull/125
